### ISSUE TITLE
Changing characters doesn't trigger a change on perks unless they are empty. 

### ISSUE THREAD

**Issue by kbarron525** [CodyCahoon/gloom#21]
Could be the $character observable in the availablePerks function.
`export const availablePerks = derived(character, ($character) => {
  if ($character === 'Spellweaver') {}`

**Comment by CodyCahoon** [comment]
Looks like the issue was the `#each` for Svelte was defaulting to use the same key, added in a unique key per character

```
<script>
  import { availablePerks, character } from '../stores.js';
  import Perk from './Perk.svelte';
</script>

{#each $availablePerks as perk, i ($character + i)} // here
  <Perk {perk} />
{/each}
```
